### ISSUE TITLE
Add package.json

### ISSUE THREAD

**Issue by sklintch** [one-signal/emoji-picker#6] opened 2015-09-05 05:26 UTC
Can we please add package.json to this project and version tags so cdnjs can host it. 

https://github.com/one-signal/emoji-picker/issues/2
https://github.com/one-signal/emoji-picker/issues/3

**Comment by gdeglin** [comment] 2015-09-09 01:39
Duplicate of #2. We'll do this soon. Thanks for the feedback!

**Closed by gdeglin** 2015-09-09 01:39 UTC
